# Generated by Django 3.0.6 on 2020-06-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200528_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('desc', models.CharField(default='', max_length=400)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
